### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by Zhouchuanwen** [17097231932/baidu-translate#1]
{'errno': 1022, 'errmsg': '访问出现异常，请刷新后重试！', 'error': 1022, 'errShowMsg': '访问出现异常，请刷新后重试！'}

**Comment by tq-xyy** [comment]
请问可以把相关代码发出来吗？我这边需要复现。（如果可以请把错误信息也附上。）
谢谢！

**Comment by tq-xyy** [comment]
我们这边有以下几个建议：
1. 我们刚刚更新了文档，您可以参考 Demo 改写代码。
2. 您可以尝试检查一下网络。
3. 不排除百度改版，但我们这边是根据百度翻译的前端代码改写的。
4. 项目代码相对于百度原版少了一个叫 Acs-Token 的请求头，但我们进行了多次测试发现不影响结果。

祝你好运！😊

**Comment by tq-xyy** [comment]
目前进展: 不是语种错误 (错误代码: 999) 或加密算法错误 (998)。还需进一步研究。

**Comment by Breeze-Zero** [comment]
o = fanyi.translate_text(temp_text, to=fanyi.Lang.ZH)
  File "baidu_translate\__init__.py", line 47, in translate_text
    raise Exception(result['errmsg'])
Exception: 访问出现异常，请刷新后重试！

辛苦您了

**Comment by tq-xyy** [comment]
访问过快，认证错误，我在并发的时候出现过。建议加锁。

PS：也有可能是缺少 _Acs-Token_，正在寻找生成方法，请关注我们的更新动态。

> PSS: 垃圾百度，为什么到我这代码就压缩加密，连个 source map 都不给，还特么是 js vm 加密。网上的文章和我看到的不能说一模一样，只能说毫无关系。

**Comment by tq-xyy** [comment]
当前进展：我们已经掌握了加密参数生成的方法，但百度明显魔改了aes加密算法，正在寻找改动地方。

PS：它的aes部分写在外部，但如何对数据处理却写在 bdjsvm 的字节码中，正在分析。

**Comment by tq-xyy** [comment]
当前进度：通过 CryptoJS 替换混淆代码，发现百度并没有修改算法，目前加密配置为 aes-cbc-pkcs7，等待进一步逆向。

**Comment by tq-xyy** [comment]
当前进展：我们已经添加了对 Acs-Token 的支持，但由于百度的奇怪行为，偶尔会出现无法访问（错误代码体现为1022或998），属正常现象（毕竟不能两全其美，要稳定服务自己去花钱买百度官方API）。

**Comment by Gia-beep** [comment]
C:/Users/x1843/Desktop/5
  0%|          | 0/1 [00:00<?, ?it/s]error occured.trying again

  0%|          | 0/1 [00:00<?, ?it/s]error occured.trying again


100%|██████████| 1/1 [00:08<00:00,  8.84s/it]
Translating error
0 files translated
1 files translated
现在需要多次进行请求才能获取到结果（运气好的时候）
我在运行示例代码进行测试时出现    raise select_error(code)(f'{msg} (code {code})')
baidu_translate.errors.TranslateError: 访问出现异常，请刷新后重试！ (code 1022)
